/*
Write a program that first reads the 6 numbers generated by the lottery and then the 6 numbers on your ticket.
The program then compares how many numbers the player got right.
Then, it allocates space for a vector of size equal to the number of correct numbers and stores the correct numbers in this vector. 
Finally, the program displays the drawn numbers and your correct numbers.
*/

#include <stdio.h>
#include <stdlib.h>

void ReadInteger( int *number );

int main() {
    int lottery[6] = { 43, 12, 2, 33, 3, 21 }, ticket[6], size = 0;
    int *correctGuess;

    // for ( int i = 0 ; i < 6; i++ ) {
    //     int ran = rand() % 11;
    //     for ( int j = 0; j < 6; j++ ){
    //         while ( ran == lottery[j] ) {
    //             ran++;
    //         }
    //     }
    //     lottery[i] = ran;
    // }

    for ( int i = 0; i < 6; i++ ) {
        printf( "Input your 6 lottery ticket numbers. Number %d: ", i+1 );
        ReadInteger( &ticket[i] );
    }
    printf("\n");

    for ( int i = 0; i < 6; i++ ) {
        for ( int j = 0; j < 6; j++ ) {
            if ( lottery[i] == ticket[j] ) {
                if ( size == 0 ) {
                    correctGuess = (int *)malloc( ++size * sizeof( int ) );
                    printf( "You got a number right! %d\n", lottery[i] );
                    correctGuess[size-1] = lottery[i];
                } else {
                    correctGuess = (int *)realloc( correctGuess, ++size * sizeof( int ) );
                    printf( "You got a number right! %d\n", lottery[i] );
                    correctGuess[size-1] = lottery[i];
                }
            }
        } 
    }

    printf("\n");
    for ( int i = 0; i < 6; i++ ) {
        printf( "Lottery: %d\n", lottery[i] );
    }
    printf("\n");

    for ( int i = 0; i < size; i++ ) {
        printf( "Your correct number: %d\n", correctGuess[i] );
    }
    printf("\n");


    printf( "Size: %d\n", size );

}

void ReadInteger( int *number ) {
    char buffer[16];
    fgets( buffer, sizeof( buffer ), stdin );
    sscanf( buffer, "%d", number );
}